/* English & Tamil Complete Bilingual Localization Dictionary for AstroVerse */

export const TRANSLATIONS = {
  en: {
    // Navigation
    appName: "AstroVerse",
    appSubtitle: "Vedic & Western Life Guidance Platform",
    navHoroscope: "Horoscope & Kundli",
    navPalm: "Palmistry (Demo)",
    navNumerology: "Numerology Matrix",
    navNames: "Kids' Name Generator",
    navBirthRecovery: "Heuristic Nashta Jataka Reconstruction",
    upgradePass: "Upgrade Pass",
    credits: "Credits",

    // Banner
    masterDossierBannerTitle: "Comprehensive Astrological & Palmistry Master Dossier",
    masterDossierBannerDesc: "All 12 Bhavas, Auspicious Yogas, Ayurvedic Tridosha Balance, and Sacred Vedic Remedies.",
    viewDetailedReport: "View Detailed Report",

    // Horoscope
    natalChartTitle: "Astronomical Natal Chart Generator",
    natalChartSubtitle: "Planetary ephemeris calculating Sun Sign, Moon Nakshatra, Ascendant (Lagna), Houses, and Dasha cycles.",
    enterBirthCoord: "Enter Your Exact Birth Coordinates",
    vedicSidereal: "Vedic (Sidereal / Lahiri)",
    westernTropical: "Western (Tropical Wheel)",
    fullName: "Full Name",
    dob: "Date of Birth",
    birthTime: "Exact Time of Birth (24h)",
    birthPlace: "Birth City / Location",
    quickLocations: "Quick Geocoded Locations:",
    calculateBtn: "Calculate Ephemeris & Birth Chart",
    currentSystem: "Current System:",

    // Sub tabs
    subTabChart: "Natal Chart & Dasha",
    subTabTimeline: "Personalized Dasha & Transit Life Timeline",
    subTabGochar: "Gochar & Sade Sati Transits",
    subTabPanchang: "Daily Panchanga & Muhurta",
    subTabMatch: "36 Guna Kundli Match",
    subTabRecovery: "Heuristic Nashta Jataka Reconstruction",

    // Signs & Triad
    sunSignTitle: "Sun Sign (Surya)",
    sunSignDesc: "Core Identity, Vital Will & Soul Purpose",
    moonSignTitle: "Moon Sign (Chandra)",
    moonSignDesc: "Deep subconscious mind, psychic intuition, and emotional peace.",
    ascendantTitle: "Ascendant (Lagna)",
    ascendantDesc: "Outer Persona, Health, & World View",
    element: "Element:",
    ruler: "Ruler:",
    nakshatraLabel: "Nakshatra:",
    lordLabel: "Lord:",
    syllableLabel: "Syllable:",
    qualityLabel: "Quality:",
    house1Cusps: "House 1 Cusps: Active",

    // Kundli chart
    natalKundliTitle: "Natal Kundli Chart",
    southStyle: "South Indian Style (Box)",
    northStyle: "North Indian Style (Diamond)",
    southExpl: "South Indian Chart: Zodiac signs are fixed in clockwise order starting from Pisces (top-left) to Aquarius.",
    northExpl: "North Indian Chart: Houses are fixed (House 1 at top center diamond), with signs rotating based on Ascendant.",
    ephemerisTitle: "Planetary Ephemeris Longitudes",
    activeDashaTitle: "Active Vimshottari Mahadasha",
    activeDashaBadge: "Favorable Transit",
    activeDashaDesc: "Major expansions in intellect, reputation, and commercial ventures under Jupiter/Mercury alignments.",

    // Timeline
    sixStageTitle: "Personalized Dasha & Transit Predictive Life Timeline",
    personalizedTimelineTitle: "Personalized Dasha & Transit Predictive Life Timeline",
    sixStageDesc: "Synthesizing natal planetary house strengths, major transits (Guru/Shani), and Vimshottari Dasha windows.",
    personalizedTimelineDesc: "Synthesizing natal planetary house strengths, major transits (Guru/Shani), and Vimshottari Dasha windows.",

    // Match
    matchHeaderTag: "36 Guna Ashtakoota Milan",
    matchMainTitle: "Vedic Relationship & Marriage Compatibility",
    matchMainDesc: "Traditional 8-Kuta compatibility analyzing classical cultural alignment, temperamental resonance, and traditional family harmony.",
    partner1: "Partner 1",
    partner2: "Partner 2",
    groom: "Groom (Boy / Var)",
    bride: "Bride (Girl / Kanya)",
    groomShort: "Groom (Boy)",
    brideShort: "Bride (Girl)",
    swapRoles: "Swap Groom / Bride Roles",
    partnerRole: "Role in Compatibility",
    selectGender: "Select Gender",
    male: "Male (Boy)",
    female: "Female (Girl)",
    birthMoonNak: "Birth Moon Nakshatra",
    matchBtn: "Analyze 36-Point Compatibility",
    matchScoreTitle: "Overall Compatibility Rating",
    matchThreshold: "Traditional Ashtakoota reference threshold: 18/36. This score is one traditional compatibility framework and is not a validated predictor of relationship outcome.",
    matchLabel: "Match",

    // Palmistry
    palmTitle: "Classical Samudrika Palmistry Reference",
    palmDesc: "Explore major lines (Heart, Head, Life, Fate) and mount elevations using classical Samudrika archetypes.",
    leftHand: "Left Hand (Innate Potential)",
    rightHand: "Right Hand (Active Destiny)",
    readyToScan: "Ready for Palm Analysis",
    scanInstruction: "Align palm inside the guide silhouette or upload a clear photo for reference analysis.",
    launchCamera: "Launch Camera",
    uploadPalm: "Upload Palm Photo",
    demoScan: "Instant Reference Demo",
    verifiedReading: "Illustrative Palmistry Reading",
    accuracy: "Evidence Strength",
    downloadReport: "Download PDF Report",
    scanOtherHand: "Scan Other Hand",
    elementalShape: "Elemental Hand Shape",
    dominantMount: "Dominant Mount",
    primaryArc: "Primary Life Path Mark",
    emotionalPattern: "Emotional & Relationship Pattern",
    careerDrive: "Career & Intellectual Drive",
    vitalityHealth: "Traditional Palmistry Wellness Themes",
    mountElevations: "Mount Elevations & Planetary Influences",
    mountDesc: "The flesh cushions beneath your fingers measure cosmic energy absorption per classical palmistry.",
    karmicDualityTitle: "Ancient Palmistry Principle: Karmic Potential vs. Manifested Reality",
    karmicDualityDesc: "In traditional chiromancy, your non-dominant hand (usually Left) carries your raw spiritual inheritance, inborn potential, and karmic blueprints. Your dominant hand (usually Right) records your conscious decisions, lifestyle evolution, and actualized destiny. Compare both scans to witness how much your will has transformed your baseline fortune.",
    detectedLineVectors: "Detected Line Vectors & Manual Touch-Up",
    confidence: "Reading Mode",

    // Numerology
    numTitle: "Sacred Vibrational Numerology",
    numMainTitle: "Life Path, Destiny & Daily Cycle Matrix",
    numDesc: "Decode your cosmic vibration using Pythagorean and ancient Chaldean letter-to-number algorithms.",
    pythagoreanSystem: "Pythagorean System",
    chaldeanSystem: "Ancient Chaldean System",
    fullBirthName: "Full Birth Certificate Name",
    recalculateNum: "Recalculate Numerology Blueprint",
    lifePathTitle: "Life Path Number",
    destinyTitle: "Destiny Number",
    soulUrgeTitle: "Soul Urge (Vowels)",
    soulUrgeDesc: "Drives your most intimate motivations, unspoken passions, and deep spiritual contentment.",
    personalityTitle: "Personality (Consonants)",
    personalityDesc: "How strangers and colleagues perceive your energy and charisma in first encounters.",
    forecastCycleTitle: "Numerological Personal Forecast Cycles",
    personalYear: "Current Year Cycle",
    personalYearDesc: "A cycle dedicated to strategic consolidation, financial breakthroughs, and career leadership.",
    personalMonth: "Current Month Cycle",
    personalMonthDesc: "High social energy, networking opportunities, and fertile ground for negotiations.",
    personalDay: "Today's Vibration",
    personalDayDesc: "Auspicious for launching new projects, contracts, and creative declarations.",
    luckyNumbers: "Lucky Numbers",
    powerColors: "Power Colors",
    gemstones: "Resonant Gemstones",

    // Baby Names
    babyTitle: "Auspicious Newborn Naming Engine",
    babyMainTitle: "Nakshatra Pada & Numerological Name Matcher",
    babyDesc: "Discover meaningful names synchronized with your baby’s birth nakshatra sound syllables and family surname numerological vibration.",
    newbornNamakarana: "Newborn Vedic Namakarana & Horoscope",
    newbornNamakaranaDesc: "Enter baby's Initial, Gender, Date of Birth, Time, and Place to compute the exact Moon Star Pada, sacred starting syllables, numerological resonance, and astrologically empowering names.",
    babyInitial: "Child's Initial",
    babyDob: "Date of Birth",
    babyTime: "Exact Time of Birth",
    babyPlace: "Place of Birth",
    calculateNewbornNames: "Calculate Horoscope & Auspicious Names",
    nakshatraPada: "Moon Nakshatra & Pada",
    auspiciousSyllables: "Auspicious Starting Syllable (அட்சரம்)",
    allPadaSyllables: "All 4 Pada Syllables for Star",
    driverDestiny: "Driver (Mulank) & Destiny (Bhagyank)",
    whySuggested: "Why This Name is Suggested & Empowering",
    aiDeepSynthesis: "AI Bespoke Name Synthesis",
    aiGenerating: "Synthesizing auspicious names with Gemini AI...",
    generateAiNamesBtn: "Generate Rare & Modern AI Names with Gemini",
    newbornKundliTitle: "Newborn Astrological Alignment",
    numerologyHarmony: "Chaldean Numerology Harmony",
    genderLabel: "Gender",
    cultureLabel: "Culture / Tradition",
    nakshatraFilter: "Birth Nakshatra (Vedic)",
    surnameLabel: "Family Surname",
    allGenders: "All Genders",
    babyBoy: "Baby Boy",
    babyGirl: "Baby Girl",
    unisex: "Unisex",
    allTraditions: "All Traditions",
    vedicSanskrit: "Vedic / Sanskrit",
    westernModern: "Western / Modern",
    arabicTradition: "Arabic / Middle Eastern",
    universalTradition: "Universal / Global",
    anyNakshatra: "Any Nakshatra",
    auspiciousSoundsFor: "Auspicious starting sounds for",
    savedShortlist: "Saved Shortlist",
    noNamesShortlisted: "No names shortlisted yet",
    shareWithFamily: "Share with Family to Vote",
    destinyNo: "Destiny No:",
    harmony: "Harmony",
    familyVotes: "family votes",
    copyLink: "Copy Link",
    votingModalTitle: "Family Shortlist Voting Link",
    votingModalDesc: "Send this private link to your family via WhatsApp, iMessage, or Telegram. Each relative can upvote their favorites!",

    // Pricing & Monetization
    pricingTag: "AstroVerse Membership Plans",
    pricingTitle: "Choose Your Sacred Guidance Pass",
    pricingDesc: "Unlock comprehensive palmistry reference, Vedic Kundli, Nakshatra baby name engines, and planetary ephemeris reports.",
    monthlyBilling: "Monthly Billing",
    yearlyBilling: "Yearly (Save 30%)",
    currencyLabel: "Currency:",
    recommended: "Recommended",
    selectedPlan: "Selected Plan",
    choosePlan: "Choose Plan",
    selectPaymentMethod: "Select Payment Method (Global & Regional)",
    authorizeUnlock: "Authorize & Unlock Pro Access",
    subscriptionActivated: "Subscription Activated Successfully!",
    securityNotice: "Astronomical calculations performed locally • AI reports processed through secure API • Cancel anytime.",

    // Shodashavarga & Retrospective Audit
    retrospectiveAuditTitle: "Retrospective Life Milestone Audit",
    retrospectiveAuditSubtitle: "Cross-verify calculated Dasha-Bukthi periods against past real-life milestones (education, marriage, career, property, family)",
    retrospectiveAuditSeniorNote: "Senior Verification Checklist: Validate historical events before predicting for younger generations.",
    vargaD1: "Rashi (D1) - Physical Body & General Destiny",
    vargaD2: "Hora (D2) - Wealth, Resources & Prosperity",
    vargaD3: "Drekkana (D3) - Siblings, Courage & Vitality",
    vargaD4: "Chaturthamsha (D4) - Fortune, Land & Fixed Assets",
    vargaD7: "Saptamsha (D7) - Children, Lineage & Dynastic Continuity",
    vargaD9: "Navamsha (D9) - Dharma, Marriage & Inner Soul Nature",
    vargaD10: "Dasamsha (D10) - Great Deeds, Career & Public Status",
    vargaD12: "Dvadasamsha (D12) - Parents, Ancestry & Lineage Karma",
    vargaD16: "Shodashamsha (D16) - Vehicles, Luxuries & Happiness",
    vargaD20: "Vimsamsha (D20) - Spiritual Progress, Upasana & Devotion",
    vargaD24: "Chaturvimsamsha (D24) - Higher Learning, Knowledge & Scholastic Intellect",
    vargaD27: "Saptavimsamsha (D27) - Strengths, Vulnerabilities & Resilience (Bhamsa)",
    vargaD30: "Trimsamsha (D30) - Misfortunes, Evils & Karmic Hazards",
    vargaD40: "Khavedamsha (D40) - Auspicious & Inauspicious Karmic Effects",
    vargaD45: "Akshavedamsha (D45) - General Well-Being & All Manifestations",
    vargaD60: "Shashtiamsha (D60) - Traditional Karmic Themes & Root Karmic Blueprint",

    // Disclaimer
    disclaimerLabel: "Statutory Guidance & App Store Compliance Disclaimer:",
    disclaimerText: "AstroVerse provides astrological calculations, Vedic ephemeris readings, palm line analyses, and numerology projections purely for personal entertainment, self-reflection, and spiritual insight. Content should never replace qualified professional advice (legal, medical, or financial).",
    dismiss: "Dismiss",
    encrypted: "Client-Side Privacy & Secure HTTPS",
    complianceBadge: "Compliance & Disclaimer"
  },
  ta: {
    // Navigation
    appName: "ஆஸ்ட்ரோவெர்ஸ்",
    appSubtitle: "வேத ஜோதிடம், கைரேகை & எண் கணித வழிகாட்டி",
    navHoroscope: "ஜாதகம் & குண்டலி",
    navPalm: "கைரேகை (முன்வடிவம்)",
    navNumerology: "எண் கணித மேட்ரிக்ஸ்",
    navNames: "குழந்தை பெயர் தேர்வு",
    navBirthRecovery: "பாரம்பரிய உத்தேச நஷ்ட ஜாதக மறுகட்டமைப்பு",
    upgradePass: "பிரீமியம் பாஸ்",
    credits: "கிரெடிட்ஸ்",

    // Banner
    masterDossierBannerTitle: "முழுமையான ஜாதக-கைரேகை மகா அறிக்கை (Exhaustive Master Dossier)",
    masterDossierBannerDesc: "12 பாவக முழு பலன்கள், கஜகேசரி/புத-ஆதித்ய யோகங்கள், ஆயுர்வேத திரிதோஷ சமநிலை மற்றும் ரத்தின பரிகாரங்கள்.",
    viewDetailedReport: "முழு அறிக்கையை காண்க",

    // Horoscope
    natalChartTitle: "துல்லியமான வேத ஜனன ஜாதக கணிப்பான்",
    natalChartSubtitle: "சூரிய ராசி, சந்திர நட்சத்திர பாதம், லக்னம், 12 பாவகங்கள் மற்றும் விம்சோத்தரி தசா இருப்பை துல்லியமாக கணக்கிடுகிறது.",
    enterBirthCoord: "பிறந்த தேதி, நேரம் மற்றும் ஊரை உள்ளிடவும்",
    vedicSidereal: "வேத ஜோதிடம் (திருக்கணிதம் / லஹிரி)",
    westernTropical: "மேற்கத்திய முறை (Western Wheel)",
    fullName: "முழு பெயர்",
    dob: "பிறந்த தேதி",
    birthTime: "பிறந்த துல்லிய நேரம் (24 மணி)",
    birthPlace: "பிறந்த ஊர் / நகரம்",
    quickLocations: "விரைவு முக்கிய நகரங்கள்:",
    calculateBtn: "ஜாதகம் & நவகிரக நிலைகளை கணக்கிடு",
    currentSystem: "தற்போதைய முறை:",

    // Sub tabs
    subTabChart: "ஜாதக கட்டம் & தசா இருப்பு",
    subTabTimeline: "விம்சோத்தரி தசா-புக்தி & கோச்சார வாழ்க்கை காலக்கோடு",
    subTabGochar: "கோச்சாரம் & ஏழரை சனி",
    subTabPanchang: "தினசரி பஞ்சாங்கம் & முகூர்த்தம்",
    subTabMatch: "36 குண திருமண பொருத்தம்",
    subTabRecovery: "பாரம்பரிய உத்தேச நஷ்ட ஜாதக மறுகட்டமைப்பு",

    // Signs & Triad
    sunSignTitle: "சூரிய ராசி (Surya Rasi)",
    sunSignDesc: "ஆன்ம காரகன், ஆளுமைத் திறன், கௌரவம் மற்றும் தலைமைப் பண்பு",
    moonSignTitle: "சந்திர ராசி & நட்சத்திரம்",
    moonSignDesc: "மனோகாரகன், ஆழமான உள்ளுணர்வு, சிந்தனை ஓட்டம் மற்றும் மன அமைதி.",
    ascendantTitle: "லக்னம் (Lagna / Ascendant)",
    ascendantDesc: "உடலமைப்பு, வெளி உலக தோற்றம், ஆரோக்கியம் மற்றும் வாழ்க்கை பார்வை",
    element: "தத்துவம்:",
    ruler: "அதிபதி:",
    nakshatraLabel: "நட்சத்திரம்:",
    lordLabel: "அதிபதி:",
    syllableLabel: "அட்சரம்:",
    qualityLabel: "குணம்:",
    house1Cusps: "1-ம் பாவ முனை: சுப பலம்",

    // Kundli chart
    natalKundliTitle: "ஜனன ஜாதக கட்டம்",
    southStyle: "தென்னிந்திய கட்டம் முறை",
    northStyle: "வடஇந்திய வைரம் முறை",
    southExpl: "தென்னிந்திய கட்டம் முறை: மீனம் (மேல்-இடது) முதல் கும்பம் வரை ராசிகள் கடிகார சுற்றில் நிலையாக அமைந்திருக்கும்.",
    northExpl: "வடஇந்திய வைரம் முறை: பாவகங்கள் நிலையானவை (மேல் மையம் லக்னம் 1-ம் பாவம்), லக்னத்திற்கு ஏற்ப ராசிகள் மாறும்.",
    ephemerisTitle: "நவகிரக பாகை மற்றும் இருப்பு நிலைகள்",
    activeDashaTitle: "தற்போது நடக்கும் விம்சோத்தரி மகா தசை",
    activeDashaBadge: "சுப கிரக சஞ்சாரம்",
    activeDashaDesc: "குரு மற்றும் புதன் அனுகூலத்தால் அறிவு வளர்ச்சி, புதிய முயற்சிகள், நற்பெயர் மற்றும் நிதி முன்னேற்றம் உண்டாகும்.",

    // Timeline
    sixStageTitle: "விம்சோத்தரி தசா-புக்தி & கோச்சார வாழ்க்கை காலக்கோடு",
    personalizedTimelineTitle: "விம்சோத்தரி தசா-புக்தி & கோச்சார வாழ்க்கை காலக்கோடு",
    sixStageDesc: "ஜாதக பாவ பலம், முக்கிய கிரக பெயர்ச்சிகள் (குரு/சனி) மற்றும் தசா புக்தி கால கட்டங்களை ஒருங்கிணைத்து கணிக்கப்பட்டது.",
    personalizedTimelineDesc: "ஜாதக பாவ பலம், முக்கிய கிரக பெயர்ச்சிகள் (குரு/சனி) மற்றும் தசா புக்தி கால கட்டங்களை ஒருங்கிணைத்து கணிக்கப்பட்டது.",

    // Match
    matchHeaderTag: "36 குண அஷ்டகூட திருமணப் பொருத்தம்",
    matchMainTitle: "வேத முறை தம்பதியர் திருமணப் பொருத்தம்",
    matchMainDesc: "பாரம்பரிய கலாச்சார இசைவு, மனோபாவப் பொருத்தம் மற்றும் குடும்ப நல்லிணக்கத்தை ஆராயும் 8-கூட பாரம்பரிய சாஸ்திர மதிப்பீடு.",
    partner1: "முதல் ஜாதகர் (Partner 1)",
    partner2: "இரண்டாம் ஜாதகர் (Partner 2)",
    groom: "மணமகன் (Boy / வரன்)",
    bride: "மணமகள் (Girl / கன்யா)",
    groomShort: "மணமகன் (Boy)",
    brideShort: "மணமகள் (Girl)",
    swapRoles: "மணமகன் / மணமகள் நிலையை மாற்றுக",
    partnerRole: "பொருத்தப் பங்கு",
    selectGender: "பாலினத் தேர்வு",
    male: "ஆண் (மணமகன்)",
    female: "பெண் (மணமகள்)",
    birthMoonNak: "ஜென்ம சந்திர நட்சத்திரம்",
    matchBtn: "36-புள்ளி அஷ்டகூட பொருத்தத்தை ஆராய்க",
    matchScoreTitle: "மொத்த திருமண பொருத்த மதிப்பீடு",
    matchThreshold: "பாரம்பரிய அஷ்டகூட வழிகாட்டுதல் வரம்பு: 18/36. இது ஒரு பாரம்பரிய ஒப்பீட்டு முறையே தவிர, திருமண நல்வாழ்வின் உத்தரவாதமல்ல.",
    matchLabel: "பொருத்தம்",

    // Palmistry
    palmTitle: "சாமுத்ரிக லட்சண கைரேகை குறிப்பு",
    palmDesc: "முக்கிய ரேகைகள் (ஆயுள், புத்தி, இருதயம், விதி) மற்றும் கிரக மேடுகளை பாரம்பரிய சாமுத்ரிகா முறையில் ஆராய்க.",
    leftHand: "இடது கை (பிறவி யோகம் & பூர்வ புண்ணியம்)",
    rightHand: "வலது கை (செயல் விதி & தற்கால வாழ்க்கை)",
    readyToScan: "கைரேகை மாதிரி ஆய்வுக்கு தயார்",
    scanInstruction: "வழிகாட்டி கோட்டிற்குள் கையை வைக்கவும் அல்லது புகைப்படத்தை பதிவேற்றவும்.",
    launchCamera: "கேமராவை திறக்கவும்",
    uploadPalm: "கைரேகை புகைப்படத்தை பதிவேற்று",
    demoScan: "உடனடி மாதிரி ஆய்வு",
    verifiedReading: "விளக்கக் கைரேகை பார்வை (மாதிரி ஆய்வு)",
    accuracy: "ஆதார வலிமை",
    downloadReport: "PDF அறிக்கையை பதிவிறக்கு",
    scanOtherHand: "மறு கையை ஸ்கேன் செய்ய",
    elementalShape: "பூத கை வடிவம்",
    dominantMount: "ஆதிக்க கிரக மேடு",
    primaryArc: "முதன்மை ஆயுள் ரேகை அமைப்பு",
    emotionalPattern: "மன உணர்வு & உறவுமுறை போக்கு",
    careerDrive: "தொழில் வெற்றி & புத்தி கூர்மை",
    vitalityHealth: "பாரம்பரிய கைரேகை நல்வாழ்வு குறிப்புகள் (Wellness Themes)",
    mountElevations: "கிரக மேடுகள் & பிரபஞ்ச ஆற்றல்",
    mountDesc: "விரல்களின் அடியில் உள்ள மேடுகள் பாரம்பரிய சாஸ்திரப்படி கிரக கதிர்வீச்சு ஈர்ப்பை குறிக்கின்றன.",
    karmicDualityTitle: "கைரேகை சாஸ்திர நியதி: பூர்வ புண்ணியம் vs செயல் விதி",
    karmicDualityDesc: "பாரம்பரிய சாமுத்ரிகா லட்சணப்படி, செயல்படாத கை (இடது கை) உங்களின் பூர்வ புண்ணியம், பரம்பரை குணங்கள் மற்றும் உள்ளார்ந்த ஆற்றலை காட்டுகிறது. செயல்படும் கை (வலது கை) உங்களின் சுய முயற்சி, எடுத்த முடிவுகள் மற்றும் மாற்றியமைக்கப்பட்ட விதியை காட்டுகிறது. இரண்டையும் ஒப்பிட்டு உங்கள் விதியை நீங்களே எவ்வாறு மேம்படுத்தியுள்ளீர்கள் என்பதை அறியலாம்.",
    detectedLineVectors: "கண்டறியப்பட்ட ரேகைகள் & திருத்தங்கள்",
    confidence: "வாசிப்பு முறை",

    // Numerology
    numTitle: "புனித அதிர்வு எண் கணிதம் (Numerology)",
    numMainTitle: "ஆயுள் எண், பெயர் விதி எண் & தினசரி சுழற்சி",
    numDesc: "பித்தகோரியன் மற்றும் பண்டைய சால்டியன் (Chaldean) ரகசிய எண் சூத்திரங்களை கொண்டு உங்கள் அதிர்வை கண்டறியவும்.",
    pythagoreanSystem: "பித்தகோரியன் முறை",
    chaldeanSystem: "பண்டைய சால்டியன் முறை",
    fullBirthName: "பிறப்பு சான்றிதழில் உள்ள முழு பெயர்",
    recalculateNum: "எண் கணித பலனை மறு கணக்கீடு செய்க",
    lifePathTitle: "ஆயுள் எண் (Life Path)",
    destinyTitle: "விதி எண் / பெயர் எண் (Destiny)",
    soulUrgeTitle: "ஆன்ம எண் (Soul Urge - உயிரெழுத்துக்கள்)",
    soulUrgeDesc: "உங்களின் ஆழ்ந்த ஆசைகள், ரகசிய லட்சியங்கள் மற்றும் மன அமைதியை தீர்மானிக்கிறது.",
    personalityTitle: "ஆளுமை எண் (Personality - மெய்யெழுத்துக்கள்)",
    personalityDesc: "வெளி உலகம் மற்றும் புதிய நபர்கள் உங்களை முதல் பார்வையில் எவ்வாறு உணர்கிறார்கள் என்பதை குறிக்கிறது.",
    forecastCycleTitle: "எண் கணித கால சுழற்சி பலன்கள்",
    personalYear: "நடப்பு ஆண்டு பலன்",
    personalYearDesc: "தொழில் முதலீடுகள், பொருளாதார வளர்ச்சி மற்றும் புதிய சாதனைகளுக்கான ஆண்டு.",
    personalMonth: "நடப்பு மாத அதிர்வு",
    personalMonthDesc: "சமூக நட்பு வட்டம், பேச்சுவார்த்தைகள் மற்றும் ஒப்பந்தங்களுக்கான அனுகூல மாதம்.",
    personalDay: "இன்றைய அதிர்ஷ்ட நாள் எண்",
    personalDayDesc: "புதிய பணிகளை தொடங்கவும், ஆவணங்களில் கையொப்பமிடவும் ஏற்ற தினம்.",
    luckyNumbers: "அதிர்ஷ்ட எண்கள்",
    powerColors: "அதிர்ஷ்ட வண்ணங்கள்",
    gemstones: "அதிர்ஷ்ட ரத்தினக் கற்கள்",

    // Baby Names
    babyTitle: "மங்கலகரமான குழந்தை பெயர்கள் ஜெனரேட்டர்",
    babyMainTitle: "நட்சத்திர பாத மங்கல அட்சரங்கள் & எண் கணித பெயர் தேர்வு",
    babyDesc: "குழந்தையின் ஜென்ம நட்சத்திர பாத ஆரம்ப ஒலி மற்றும் குடும்ப பெயருடன் முழுமையாக பொருந்தும் சுப பெயர்களை கண்டறியுங்கள்.",
    newbornNamakarana: "புதிதாகப் பிறந்த குழந்தைகளுக்கான வேத நாமகரணம் & ஜாதகம்",
    newbornNamakaranaDesc: "குழந்தையின் இனிஷியல், பாலினம், பிறந்த தேதி, நேரம் மற்றும் ஊரை உள்ளிட்டு துல்லியமான நட்சத்திர பாதம், அதிர்ஷ்ட தொடக்க அட்சரங்கள், எண் கணித பொருத்தம் மற்றும் யோக பலன் தரும் பெயர்களை கண்டறியவும்.",
    babyInitial: "குழந்தையின் இனிஷியல்",
    babyDob: "பிறந்த தேதி",
    babyTime: "பிறந்த நேரம்",
    babyPlace: "பிறந்த ஊர் / நகரம்",
    calculateNewbornNames: "குழந்தை ஜாதகம் & சுப பெயர்களை கணக்கிடு",
    nakshatraPada: "சந்திர நட்சத்திரம் & பாதம்",
    auspiciousSyllables: "அதிர்ஷ்ட தொடக்க அட்சரம் (முதல் எழுத்து)",
    allPadaSyllables: "நட்சத்திரத்தின் 4 பாத அட்சரங்கள்",
    driverDestiny: "சுப எண்கள் (Driver எண் & விதி எண்)",
    whySuggested: "இந்த பெயர் பரிந்துரைக்கப்பட்டதற்கான சாஸ்திர காரணம் & நன்மைகள்",
    aiDeepSynthesis: "AI வேத நாமகரண பெயர் ஜெனரேட்டர்",
    aiGenerating: "Gemini AI மூலம் புதிய சுப பெயர்கள் உருவாக்கப்படுகின்றன...",
    generateAiNamesBtn: "Gemini AI மூலம் தனிப்பயன் நவீன & அரிய பெயர்களை பெறுக",
    newbornKundliTitle: "குழந்தையின் ஜனன ஜாதக கிரக அமைப்பு",
    numerologyHarmony: "கால்டியன் எண் கணித பொருத்தம்",
    genderLabel: "பாலினம்",
    cultureLabel: "கலாச்சாரம் / பாரம்பரியம்",
    nakshatraFilter: "ஜென்ம நட்சத்திரம் (Vedic)",
    surnameLabel: "குடும்ப பெயர் (Surname)",
    allGenders: "அனைத்து பாலினமும்",
    babyBoy: "ஆண் குழந்தை",
    babyGirl: "பெண் குழந்தை",
    unisex: "பொதுவான பெயர்",
    allTraditions: "அனைத்து பாரம்பரியமும்",
    vedicSanskrit: "வேத / தமிழ் / சமஸ்கிருதம்",
    westernModern: "மேற்கத்திய / நவீன பெயர்கள்",
    arabicTradition: "அரபு / மத்திய கிழக்கு",
    universalTradition: "உலகளாவிய பொது பெயர்கள்",
    anyNakshatra: "எல்லா நட்சத்திரமும்",
    auspiciousSoundsFor: "மங்கலகரமான ஆரம்ப எழுத்து ஒலிகள்:",
    savedShortlist: "தேர்வு செய்யப்பட்ட பெயர்கள்",
    noNamesShortlisted: "இன்னும் பெயர்கள் தேர்வு செய்யப்படவில்லை",
    shareWithFamily: "குடும்பத்தினருடன் பகிர்ந்து வாக்களிக்க",
    destinyNo: "பெயர் எண்:",
    harmony: "பொருத்தம்",
    familyVotes: "குடும்ப வாக்குகள்",
    copyLink: "இணைப்பை நகலெடு",
    votingModalTitle: "குடும்பத்தினர் வாக்களிக்கும் ரகசிய இணைப்பு",
    votingModalDesc: "இந்த இணைப்பை WhatsApp அல்லது Telegram மூலம் உங்கள் குடும்பத்தினருக்கு அனுப்பி விருப்பமான பெயரை தேர்வு செய்ய வையுங்கள்!",

    // Pricing & Monetization
    pricingTag: "ஆஸ்ட்ரோவெர்ஸ் உறுப்பினர் திட்டங்கள்",
    pricingTitle: "உங்களுக்கான ஜோதிட சேவையை தேர்வு செய்யவும்",
    pricingDesc: "முழுமையான கைரேகை ஸ்கேன், வேத குண்டலி, குழந்தை பெயர் தேர்வு மற்றும் வாழ்நாள் ஜாதக அறிக்கைகளை அன்லாக் செய்யுங்கள்.",
    monthlyBilling: "மாதாந்திர கட்டணம்",
    yearlyBilling: "வருடாந்திர கட்டணம் (30% சேமிப்பு)",
    currencyLabel: "நாணயம்:",
    recommended: "சிறந்த திட்டம்",
    selectedPlan: "தேர்ந்தெடுக்கப்பட்டது",
    choosePlan: "திட்டத்தை தேர்வு செய்க",
    selectPaymentMethod: "பணம் செலுத்தும் முறையை தேர்வு செய்க (UPI / NetBanking / CBDC)",
    authorizeUnlock: "பிரீமியம் சேவையை அன்லாக் செய்க",
    subscriptionActivated: "உறுப்பினர் சேர்க்கை வெற்றிகரமாக முடிந்தது!",
    securityNotice: "வான கணிதக் கணக்கீடுகள் உள்ளூரில் செயல்படும் • AI அறிக்கைகள் பாதுகாப்பான API வழியாக • எப்போதும் ரத்து செய்யலாம்.",

    // Shodashavarga & Retrospective Audit
    retrospectiveAuditTitle: "கடந்த கால வாழ்வியல் மைல்கற்கள் சரிபார்ப்பு",
    retrospectiveAuditSubtitle: "முந்தைய வாழ்க்கையின் முக்கிய சம்பவங்களை (கல்வி, திருமணம், தொழில் மாற்றம், புத்திரப்பேறு, சொத்து) தசா-புக்திகளோடு ஒப்பிட்டு சரிபார்க்கவும்",
    retrospectiveAuditSeniorNote: "முதியோருக்கான உண்மை சரிபார்ப்பு: இளைய தலைமுறையினருக்கு கணிப்பதற்கு முன் உங்கள் முந்தைய வாழ்க்கையோடு ஒப்பிட்டு உறுதிப்படுத்தவும்.",
    vargaD1: "ராசி (D1) - ஸ்தூல தேகம் & பொது விதி",
    vargaD2: "ஹோரை (D2) - செல்வம் & தன யோகம்",
    vargaD3: "திரேக்காணம் (D3) - உடன்பிறப்பு & தைரியம்",
    vargaD4: "சதுர்த்தாம்சம் (D4) - அதிர்ஷ்டம் & பூமி யோகம்",
    vargaD7: "சப்தாம்சம் (D7) - புத்திர பாக்கியம் & வம்ச விருத்தி",
    vargaD9: "நவாம்சம் (D9) - தர்மம், களத்திரம் & ஆன்ம ஆளுமை",
    vargaD10: "தசாம்சம் (D10) - தொழில் சாம்ராஜ்யம் & சமூக அந்தஸ்து",
    vargaD12: "துவாதசாம்சம் (D12) - தாய்-தந்தை & பூர்வீக கர்மா",
    vargaD16: "ஷோடசாம்சம் (D16) - வாகன யோகம் & சுகபோகங்கள்",
    vargaD20: "விம்சாம்சம் (D20) - உபாசனை, பக்தி & ஆன்மீக சாதனை",
    vargaD24: "சதுர்விம்சாம்சம் (D24) - உயர்கல்வி, வித்தை & அறிவுசார் மேதைமை",
    vargaD27: "சப்தவிம்சாம்சம் (D27) - பலம், பலவீனம் & தாங்கும் திறன்",
    vargaD30: "திரிம்சாம்சம் (D30) - அரிஷ்டங்கள், விபத்துக்கள் & தோஷங்கள்",
    vargaD40: "கவேதாம்சம் (D40) - சுபாசுப கர்மா பலன்கள்",
    vargaD45: "அக்ஷவேதாம்சம் (D45) - சர்வ மங்கள யோகம்",
    vargaD60: "ஷஷ்டியாம்சம் (D60) - பாரம்பரிய கர்ம வினைகள் & மூல கர்ம விதி",

    // Disclaimer
    disclaimerLabel: "சட்டரீதியான ஜோதிட வழிகாட்டல் மற்றும் விழிப்புணர்வு அறிவிப்பு:",
    disclaimerText: "ஆஸ்ட்ரோவெர்ஸ் வழங்கும் வேத ஜோதிட கணக்கீடுகள், கைரேகை ஆய்வுகள் மற்றும் எண் கணித பலன்கள் யாவும் சுய சிந்தனை, ஆன்மீக புரிதல் மற்றும் வழிகாட்டலுக்காக மட்டுமே வழங்கப்படுகிறது. இது சட்ட, மருத்துவ அல்லது நிதி நிபுணர்களின் ஆலோசனைகளுக்கு மாற்றாகாது.",
    dismiss: "மூடுக",
    encrypted: "தனிப்பட்ட பாதுகாப்பான இணைப்பு (HTTPS)",
    complianceBadge: "விதிமுறைகள் & அறிவிப்பு"
  }
};
